IL-57: Updated message_thread UI
bnelson777/id.ly pull request #56
Opened 2018-04-29 05:59 UTC by vanctran

* Uses the new react-native-gifted-chat component [here](https://github.com/FaridSafi/react-native-gifted-chat)
* Converted the old messages to use a new format to work with react-native-gifted-chat
* Added new comments to message_thread for documentation

2018-04-29 20:44 UTC, joewetton requested changes
![screen shot 2018-04-29 at 1 43 25 pm](https://user-images.githubusercontent.com/25456473/39410852-5c377928-4bb3-11e8-9b05-b2410820a3dc.png)

You have the blue and white bubbles backwards this message should be blue, and the messages coming in should be white. To test compose a new message the thread message should be in blue.

2018-04-30 05:25 UTC, vanctran commented
Fixed the message sender/receiver mixup and updated the component to properly handle the new sendmessage implementation

2018-05-01 04:26 UTC, ad25 commented
Works for me on android.
![il-57](https://user-images.githubusercontent.com/22670901/39461037-0b983c36-4cbd-11e8-8861-d13d45c654d8.png)

2018-05-01 05:21 UTC, ad25 approved these changes

2018-05-01 06:23 UTC, joewetton approved these changes

2018-05-01 06:49 UTC, merged