IL-68: Create message text box should expand as you type into it
bnelson777/id.ly pull request #62
Opened 2018-04-30 02:23 UTC by ad25

* Text-box now supports multi-line text

2018-04-30 05:34 UTC, vanctran requested changes
inputBox appears on the side and overlaps with the selectors. I'm sure this would be fixed once the selector issue is fixed but let's get some more input on this from other team members.

![il-68](https://user-images.githubusercontent.com/11451280/39415917-535b97f4-4bfd-11e8-8c4a-dc0d3f5a2623.png)

2018-05-01 01:04 UTC, ad25 commented
Sorry, I've reverted back the changes to using the text box. If those picker changes get pushed to master I'll definitely pull them into this branch for testing. Otherwise pulling this text box version shouldn't break iOS.

2018-05-01 09:02 UTC, vanctran approved these changes

2018-05-01 09:17 UTC, vanctran approved these changes
Works on Android and iOS. Waiting for further input from the team, otherwise, good to go.

EDIT: Nevermind. Good to go.

2018-05-01 09:22 UTC, merged