IL-90: Rolodex mode should show contact name instead of label
bnelson777/id.ly pull request #67
Opened 2018-05-05 21:44 UTC by hontatfai

![rolodex_name](https://user-images.githubusercontent.com/18671680/39667819-d710eaee-5072-11e8-80e8-54b9217c3369.png)
![wallet_label](https://user-images.githubusercontent.com/18671680/39667820-d8aa4fbc-5072-11e8-806a-4f5e2e5834cb.png)

2018-05-06 09:31 UTC, vanctran approved these changes
Works on iOS

2018-05-08 03:30 UTC, Nuni88 requested changes
It works on android, but could we do something like Name (Label) instead, like in create_message? If we only have the name, then it's impossible to tell at a glance which card you're looking at for a particular person, because you might have multiple cards from the same person.

Example:
![recip](https://user-images.githubusercontent.com/22757783/39736605-b0c3cffe-5235-11e8-82e8-5452f902dee7.JPG)

2018-05-08 04:44 UTC, Nuni88 approved these changes

2018-05-08 04:44 UTC, Nuni88 commented
Looks good.

2018-05-08 06:04 UTC, merged