IL-114: Add file system and file encryption
bnelson777/id.ly pull request #84
Opened 2018-05-12 03:49 UTC by Nuni88

- AsyncStorage has been replaced with with files stored in a directory.
- All actions that modify cards and messages now use the new file system.
- Cards and messages are now encrypted when written and decrypted when read.
- A key and initialization vector is generated on starting the app for AES encryption. This key is stored in the device's secure keychain/keystore for future use.
- Unused functions such as Delete and Update card have been removed.

Testing procedure:

1. Clear all data.
2. Reload and observe encrypted card and message data in console log.
3. Through wallet, go to add a card. Observe encrypted card data in console log when card is added.
4. Create a new message. Observe encrypted message data in console log when message is created.
5. Perform any other actions that access messages and cards and ensure that the forward-facing behavior is visibly unchanged.

2018-05-12 18:53 UTC, joewetton commented
![img_051efc666b66-1](https://user-images.githubusercontent.com/25456473/39960642-1c31a808-55db-11e8-8bad-ebed32b4375a.jpeg)

2018-05-12 19:17 UTC, Nuni88 commented
@joewetton Did you make sure to clear all data and reload the app first? And after clearing all data and reloading, if you look at your console log, do you see the encrypted cards and message data? It might also be useful if you could add console log lines in init after key and iv are set to get the values of them, because it might be a problem with them not being set properly.

2018-05-12 19:18 UTC, joewetton commented
When I try to add a card, seems the messages.dat and cards.dat files aren't getting made.
![screen shot 2018-05-12 at 12 16 25 pm](https://user-images.githubusercontent.com/25456473/39960828-87c381c4-55de-11e8-8428-6aa85bb16459.png)

2018-05-12 19:27 UTC, joewetton commented
https://github.com/wkh237/react-native-fetch-blob/wiki/File-System-Access-API#encodingstring

2018-05-12 19:30 UTC, Nuni88 commented
I just saw that too. I'll try and get a fix going here for iOS.

2018-05-12 20:49 UTC, bnelson777 commented
Just tested it too for ios, same issue. Looks like you're working on a fix though. 💯

2018-05-12 21:21 UTC, Nuni88 commented
@joewetton @bnelson777 I pushed up some changes. I don't _think_ they'll fix the iOS issue, but if one of you could test to find out, that would be helpful.

2018-05-12 21:52 UTC, bnelson777 commented
@Nuni88 Sure testing now

2018-05-12 22:06 UTC, bnelson777 commented
Tried again with same issues. Seems the unhandled promise rejection error is kinda sporadic for me (showing up at random screens sometimes and not others). I tried running it on my device twice. I got the the below warning the first time but not the second time, so not sure if that helps at all..

![img_4557](https://user-images.githubusercontent.com/32649350/39961915-c27021c6-55f5-11e8-911e-6b0cc8cfcf42.PNG)

2018-05-12 22:19 UTC, Nuni88 commented
@bnelson777 I'm not sure if that warning is related or not. Googling it wasn't too helpful. This is going to be very difficult to troubleshoot without access to an iOS platform, though. If an iOS person is on campus Monday or Tuesday and has some time, maybe we could meet up to troubleshoot the iOS side?

2018-05-12 22:22 UTC, bnelson777 commented
@Nuni88 Sure I can meet up Monday, I have class in the morning but pretty much free otherwise

2018-05-12 22:23 UTC, Nuni88 commented
@bnelson777 Cool. I've got class from 2-4, but any time outside of that should be fine.

2018-05-12 22:23 UTC, joewetton commented
Narrowed down the problem I think, seems to be an issue with iv and key not being set via sensitive info.

2018-05-12 22:26 UTC, joewetton commented on app/index.js
> +            if (carddata === ''){
2018-05-12 15:16:31.956 [info][tid:com.facebook.react.JavaScript] 'key: ', undefined
2018-05-12 15:16:31.956569-0700 idly[1559:30315] 'key: ', undefined
2018-05-12 15:16:31.957 [info][tid:com.facebook.react.JavaScript] 'iv: ', undefined
2018-05-12 15:16:31.957123-0700 idly[1559:30315] 'iv: ', undefined
JSON.stringify(CardData.card) prints the cards

2018-05-12 22:26 UTC, joewetton commented on app/index.js
> +        SInfo.getItem('key', {})
Not getting set on IOS

2018-05-12 22:26 UTC, joewetton commented on app/index.js
> +                SInfo.setItem('iv', iv, {});
Diddo.

2018-05-12 23:40 UTC, Nuni88 commented
@joewetton @bnelson777 One of you want to try testing again? It looks like iOS uses undefined instead of null for keys not present, so I tried changing === null to  == null when making keys which _might_ fix it since == null catches both.

2018-05-13 21:01 UTC, joewetton commented
@Nuni88 seems that fixed the issues in componentDidMount, but now the iv and key are empty in the actions GetCards() call.

![screen shot 2018-05-13 at 2 00 39 pm](https://user-images.githubusercontent.com/25456473/39971766-1013da88-56b6-11e8-88a2-b9dfc391d2b9.png)
![screen shot 2018-05-13 at 2 00 30 pm](https://user-images.githubusercontent.com/25456473/39971767-102c70f2-56b6-11e8-8d85-b2b6808c3852.png)

2018-05-13 22:42 UTC, Nuni88 commented
@joewetton That issue should be fixed now.

2018-05-13 22:49 UTC, joewetton commented
yep it's working, except our components don't seem to be automatically updating their state like they use to. When I compose a new message and click done the inbox view isn't updated to reflect the new message.

2018-05-13 22:53 UTC, Nuni88 commented
Yeah, I think it's just an issue with the component loading and rendering before the action is complete, which might just mean we have to somehow force it to wait for the action to complete first.

2018-05-13 22:54 UTC, joewetton commented
A timeout of some kind?

2018-05-13 23:25 UTC, Nuni88 commented
Yeah, I'm not too sure. I think it's something to do with the actions doing so much async work to be able to do the encryption and decryption that it throws the timing off.

2018-05-14 19:08 UTC, joewetton requested changes
My only concern left is the redux state doesn't update after hitting clearAll() fix that and I think it's good to merge. We can add the redux refreshing issue as a bug for fixing next sprint.

2018-05-14 19:47 UTC, Nuni88 commented
@joewetton It should be clearing the redux state with clearAll now. The loading issue when modifying cards and messages should be fixed too. There are unhandled promise warnings when modifying cards or messages now though, so I'll try to get rid of those after class today, but the functionality should all be there now.

2018-05-14 19:53 UTC, joewetton commented
Great work.

2018-05-14 19:53 UTC, joewetton approved these changes

2018-05-15 02:50 UTC, Nuni88 commented
Warnings when modifying cards or messages should be gone now. New system forces the app to wait a brief period after modifying cards/messages before going to another screen to allow it to catch up.

2018-05-15 17:31 UTC, Vancev approved these changes
Everything working for android

2018-05-15 17:32 UTC, merged