IL-117: Prevent user from decrypting same message twice
bnelson777/id.ly pull request #98
Opened 2018-05-18 09:44 UTC by Vancev

I added in IL-129, the bugfix for android deep linking since the fix is necessary to test this on android. The bug seemed to be caused because when clicking on the deep link the splash screen component is called, but the lockbox displays instead. It disappears because the splash screen navigates to home. 

To test:
1. Turn the splash screen on by setting `DEBUG` to false. 
2. Ensure the splash screen appears when it should. 
3. Create a card and email it to yourself. Open click the link in the email and click decrypt. You should get a notification saying you already have that message. 
4. Modify the id field of the card json you just emailed and click the new modified link. You should be returned home and there should be a message in the log saying "couldnt find a matching public key in users cards".

2018-05-20 02:31 UTC, bnelson777 commented
I'm having an issue where the app doesn't seem to start on ios on this branch, just getting a blank screen. I have been having a lot of build issues today though so it might be just me. I'd like to confirm if @joewetton and/or @vanctran are also having this issue.
![Uploading Screen Shot 2018-05-19 at 7.28.53 PM.png…]()

2018-05-20 03:17 UTC, Vancev commented
@bnelson777 I think it isn't working because when an Android deep link is opened the splash screen is called on Android but not iOS, which is the same reason the bug was android only. I'll update it tonight and reopen

2018-05-21 07:13 UTC, vanctran requested changes
An issue on iOS:
When trying to decrypt a message I get an error. See my following comment for the error message.

2018-05-21 07:13 UTC, vanctran commented
![GitHawk Upload by vanctran](https://i.imgur.com/ULJFvij.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2018-05-21 19:57 UTC, bnelson777 approved these changes
This works for me now 👍  @vanctran I was getting that error by modifying the wrong symbol in my email when I sent the modified link, maybe it's the same issue for you?

2018-05-21 23:45 UTC, Vancev commented
I just found a bug on with my branch on android where if the app is not running and it is opened through a deep link it will open correctly, but if it is opened a second time by a deep link the app will only open and nothing will happen. I'm going to close the pull request and look into it.

2018-05-22 02:52 UTC, joewetton approved these changes
IOS looks good.

2018-05-22 03:43 UTC, ad25 commented
Passes all the tests listed on android.

Not sure if it is relate but I'm getting a bug where I cant re-import messages.
Steps to reproduce bug:

Create a identity on device 2
Scan identity from device 1
Send message to identity from default identity to scanned identity
Email message to self
Clear all data
Scan created identity from device 1
Import message from gmail

Result:
Message not shown in inbox

2018-05-22 03:46 UTC, ad25 approved these changes

2018-05-22 04:01 UTC, merged